### ISSUE TITLE
WTF is going on? I do not receive any messages

### ISSUE THREAD

**Issue by timo-hpc** [timo9067/terminal_simulator_1#1]

**Comment by timo-hpc** [comment]
@timo9067 please advise

**Comment by timo9067** [comment]
@timo-hpc C'mon man it is your project

**Comment by timo9067** [comment]
![photo_5451732165432817777_x](https://github.com/timo9067/terminal_simulator_1/assets/116159423/db97d062-fc55-4c2b-8c0b-347dfd954a83)
